# Site settings

## Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "neon"

## Localisation
locale: "en-GB"
timezone: Europe/Helsinki

## Title
title: "Sergio Vanegas"
subtitle: "ML Specialist & Linux Enthusiast"

## Website Info
name: "Sergio Vanegas"
email: "sergiovaneg@gmail.com"
description: "Personal blog and Portfolio."

## GH Info
url: https://sergiovaneg.github.io
domain: sergiovaneg.github.io
repository: "sergiovaneg/sergiovaneg.github.io"

## Masthead
logo: "https://avatars.githubusercontent.com/u/11050167?s=400&u=78f591349509757074f2e0067c392980b2cdb43e&v=4"

## Post Dates
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: true
      read_time: true
      share: true
      related: true

## Enable Search
search: true
google:
  search_engine_id: "f2eb0cea896d94f83"

## Author (Interpretable by MM Theme)
author:
  name: "Sergio Mauricio Vanegas Arias"
  avatar: "/assets/images/profile.jpg"
  bio: >-
    "Junior Researcher and Doctoral Student at Lappeenranta-Lahti University of Technology (LUT), Finland. Research interests include Machine Learning (ML) for Industrial Applications and Digital Signal Processing."
  location: "Lappeenranta, FI"
  links:
    - label: "Email"
      icon: "fa-solid fa-envelope"
      url: "mailto:sergio.vanegas.arias@lut.fi"
    - label: "LUT Profile"
      icon: "fa-solid fa-building-columns"
      url: "https://www.lut.fi/en/profiles/sergio-vanegas-arias"
    - label: "GitHub"
      icon: "fa-brands fa-github-alt"
      url: "https://github.com/sergiovaneg"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin-in"
      url: >-
        "https://www.linkedin.com/in/sergio-mauricio-vanegas-arias-5604601a3/"
    - label: "Reddit"
      icon: "fa-brands fa-reddit-alien"
      url: "https://www.reddit.com/user/DMDemon/"

## Conversion and Markdown processing
markdown: kramdown
kramdown:
  math_engine: katex

## Pagination
pagination: 5

# Build settings
incremental: true
github: [metadata]
compress_html:
  clippings: all
  ignore:
    envs: development

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate

exclude:
  - "./README.md"
  - "./_drafts/"
