# Site settings

locale: "en-GB"
timezone: Europe/Helsinki

title: "Sergio Vanegas"
subtitle: "GH Landing Page"

name: "Sergio Mauricio Vanegas Arias"
email: "sergiovaneg@gmail.com"

repository: "sergiovaneg/sergiovaneg.github.io"

author:
  name: "Sergio Mauricio Vanegas Arias"
  avatar: "/assets/images/bio-photo.jpg"
  bio: >-
    "**Sergio Mauricio Vanegas Arias** is a Junior Researcher and Doctoral Student at Lappeenranta-Lahti University of Technology (LUT), Finland. His research interests include Machine Learning (ML) for industrial applications and Digital Signal Processing."
  location: "Lappeenranta, FI"
  links:
    - label: "GitHub"
      icon: "fa-brands fa-github-alt"
      url : "https://github.com/sergiovaneg"

description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

domain: sergiovaneg.github.io
url: https://sergiovaneg.github.io

github_username: sergiovaneg

# Build settings
<<<<<<< HEAD
<<<<<<< HEAD
incremental: true
github: [metadata]
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate

# Theme Specifics
minimal_mistakes_skin: "neon"
pagination: 5
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
=======
=======
incremental: true
>>>>>>> a392918 (Got it working.)
github: [metadata]
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
<<<<<<< HEAD
>>>>>>> 914a093 (Added scss file)
=======
  - jekyll-include-cache
  - jekyll-paginate

# Theme Specifics
minimal_mistakes_skin: "neon"
pagination: 5
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
>>>>>>> a392918 (Got it working.)
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
